<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Testcontainers.MsSql" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Comptoir.Api\Comptoir.Api.csproj" />
    <ProjectReference Include="..\..\src\Comptoir.DbMigrator\Comptoir.DbMigrator.csproj" />
  </ItemGroup>
</Project>
